modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Team-Remastered/End-Remastered-Forge/issues"
[[mods]]
modId="tlc"
version="1.0.2"
displayName="The Lost Castle"
logoFile="logolc.png"
authors="Team Remastered"
description='''The Lost Castle introduces an enormous castle that you'll be able to find with the help of a map given by a journeyman cartographer.
'''
[[dependencies.tlc]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tlc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
