modLoader="javafml"
loaderVersion="[39,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Team-Remastered/End-Remastered-Forge/issues"
[[mods]]
modId="tlc"
version="1.0.0"
displayName="The Lost Castle"
logoFile="logolc.png"
authors="Team Remastered"
description='''The Lost Castle introduces an enormous castle that you'll be able to find with the help of a map given by a journeyman cartographer.
'''
[[dependencies.tlc]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tlc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
